# sample-workflow-ubuntu-latest
# docs are in the repo

name: OSSAR ubuntu-latest
on:
  push:
    branches:
      - master

jobs:
  sample:
    name: Open Source Static Analysis Runner

    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: ubuntu-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

      # Install dotnet, used by OSSAR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

      # Run open source static analysis tools
    - name: Run OSSAR
      uses: github/ossar-action@master
      id: ossar

      # Upload results to the Security tab
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
